name: Nix CI

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  nix-build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Produce APK builds
        run: |
          NIXPKGS_ALLOW_UNFREE=1 nix-shell --pure --run ". bootstrap-nix-shell.sh && ./gradlew build"

      - name: Upload debug APK
        uses: actions/upload-artifact@v3.1.2
        with:
          name: app.apk
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
